=head1 NAME

Scripts documentation.

=head1 SYNOPSIS

=over

=item B<courses_news.pl>

=item B<debian_update.pl> [-y]

=item B<downloads_sort.pl>

=item B<music_control.pl> <mpc_command>

=item B<opus_edit.pl> <path/to/directory/>

=item B<pdf_convert.pl> <path/to/directory/>

=item B<sources_search.pl> <regular_expression>

=item B<scene_builder_download.pl>

=back

=head1 DESCRIPTION

=head2 Courses News

Courses News will fetch the news section from B<courses.ece.tuc.gr>
and after formatting it, it will be displayed as a desktop
notification via libnotify.

=head2 Debian Update

Debian Update will check the connection to debian update servers and then
it will perform several tasks with apt-get:

=over

=item It will update the cache

=item It will clean downloaded packages

=item It will perform a dist-upgrade

=item It will autoremove orphaned packages

=item Also it can take the optional arguemnt -y and pass it to dist-upgrade

=back

=head2 Downloads Sort

Downloads Sort will move the files from $HOME/Downloads/ matching
the patterns found in $HOME/.config/downloads_sort.conf to their
corresponding destinations. The downloads_sort.conf syntax is a
glob pattern followed by the destination directory, for example:

    *.pdf
    Documents/
    *.opus
    Music/

=head2 Music Control

Music control will just execute the given mpc command if mpd is running.
If it isn't running it will start it and initialize certain mpc options.
For more information on mpc see B<man mpc>.

=head2 Opus Edit

Opus Edit will edit the ARTIST and TITLE tags of all opus files
in the given directory by getting the required information from
the files name. The opus file must be named in the format of
"MyArtist - MyTitle.opus", in which case it will set the ARTIST tag
to MyArtist and the TITLE tag to MySong. If any files were edited
it will move them to the Music directory in the users home folder and
if MPD is running it will refresh it.


=head2 PDF Convert

PDF Convert will convert all doc, docx, odt, ppt, pptx, odp files
in the given directory to PDF. It uses the export to PDF function
of LibreOffice, so that needs to be installed for the script to work.

=head2 Sources Search

Sources Search will search all files contents in the current directory
and all subdirectories for matches to the given perl regualar expression
and list them. Currently it searches the contents of C source and header
files as well as Python and Perl source files.

=head2 SceneBuilder Download

SceneBuilder Download will download the latest SceneBuilder JAR from
the Gluon website and place it in USER_HOME/Workspace/, while removing
the previous file if it exists.

=head1 COPYRIGHT AND LICENSE

Copyright 2017 Marios Tsolekas <marios.tsolekas@gmail.com>.

These scripts and documentation are free software under the
GPL version 3.

=cut
