=head1 NAME

Documentation of the various scripts.

=head1 SYNOPSIS

=over

=item B<courses_news.pl>

=item B<debian_update.pl> [-y]

=item B<downloads_sort.pl>

=item B<music_control.pl>

=item B<opus_edit.py>

=item B<pdf_convert.pl>

=item B<sources_search.pl>

=back

=head1 DESCRIPTION

=head2 Courses News

Courses News will fetch the news section from B<courses.ece.tuc.gr>
and after formatting it, it will be displayed as a desktop
notification via libnotify.

=head2 Debian Update

Debian Update will check the connection to debian update servers and then
it will perform several tasks with apt-get:

=over

=item It will update the cache

=item It will clean downloaded packages

=item It will perform a dist-upgrade

=item It will autoremove orphaned packages

=item  Also it can take the optional arguemnt -y and pass it to dist-upgrade

=back

=head2 Downloads Sort

=head2 Music Control

=head2 Opus Edit

=head2 PDF Convert

=head2 Sources Search

=cut
